### ISSUE TITLE
chartjs 4.4.1

### ISSUE THREAD

**Issue by yltsa** [khalidabuhakmeh/AspNetCoreSignalRCharts#1]
Hi,

I downloaded this project and updated chartjs to 4.4.1 and signalr to 8

    {
      "library": "Chart.js@4.4.1",
      "destination": "wwwroot/lib/chartjs"
    },
    {
      "library": "microsoft-signalr@8.0.0",
      "destination": "wwwroot/lib/microsoft-signalr"
    }

It shows just an empty screen..

BR, Ilkka

**Comment by khalidabuhakmeh** [comment]
@yltsa 👋 Hello. I've upgraded this repo to point to .NET 8 and use the versions you mentioned in this issue. Pull down the latest code and give it a try.

ChartJS changed a little bit, but it's not too bad. I also ended up using JSON importmap to make it a little nicer. Cheers!

**Comment by yltsa** [comment]
Hi, thanks a lot. It is working.

Have a nice weekend,
Ilkka

________________________________
